/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.statesml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StateSystemStandaloneSetup extends StateSystemStandaloneSetupGenerated {

	public static void doSetup() {
		new StateSystemStandaloneSetup().createInjectorAndDoEMFRegistration();
	}				
}
