grammar at.ac.tuwien.big.statesml.StateSystem with org.eclipse.xtext.common.Terminals

import "http://www.big.tuwien.ac.at/statesml"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

// TODO: Extend the Xtext grammar

StateSystem returns StateSystem:
	'statesystem' name=ID;

QualifiedName returns ecore::EString:
	ID (=> '.' ID)*;

EString returns ecore::EString:
	STRING;

EInt returns ecore::EInt:
	'-'? INT;
