/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.statesml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StateSystemRuntimeModule extends AbstractStateSystemRuntimeModule {
}
