/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.statesml.ui;

import at.ac.tuwien.big.statesml.statesystem.ui.internal.StatesystemActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateSystemExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StatesystemActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StatesystemActivator.getInstance().getInjector(StatesystemActivator.AT_AC_TUWIEN_BIG_STATESML_STATESYSTEM);
	}
	
}
