/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.statesml.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class StateSystemProposalProvider extends AbstractStateSystemProposalProvider {
}
