/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.statesml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StateSystemUiModule extends AbstractStateSystemUiModule {

	public StateSystemUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
