/*
 * generated by Xtext 2.10.0
 */
package at.ac.tuwien.big.statesml.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class StateSystemOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
